/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.1.2-39-g2953c6381a"
#endif /* AVUTIL_FFVERSION_H */
